export type {
  AgentStore,
  AgentConfigStore,
  SecretStore,
  SessionStore,
  MessageStore,
  MemoryProvider,
  InstructionStore,
  ScheduleStore,
  McpServerStore,
  SkillStore,
  UserStore,
  InternalStateStore,
  SandboxStore,
  PolicyStore,
  ApprovalRequestStore,
  AttachmentStore,
  AttachmentStorage,
  ModelProviderStore,
  GatewaySecretStore,
} from './interfaces.js';

export type {
  AgentRecord,
  AgentStatus,
  AgentMcpServerRecord,
  AgentSkillRecord,
  McpServerRecord,
  StoreScope,
  PersistedSessionIndexEntry,
  SessionLogEntry,
  SkillRecord,
  ScheduleRecord,
  ScheduleCreateInput,
  ScheduleUpdateInput,
  ScheduleType,
  ScheduleStatus,
  ScheduleSessionMode,
  ScheduleDelivery,
  SchedulePolicy,
  ScheduleRunRecord,
  ScheduleRunStatus,
  MemoryEntry,
  MemoryAddInput,
  MemoryUpdateInput,
  MemorySearchOptions,
  InstructionEntry,
  UserRole,
  UserRecord,
  UserIdentity,
  MessageRow,
  SandboxRecord,
  SandboxCreateInput,
  SandboxStatus,
  SandboxType,
  PolicyEffect,
  PolicyRecord,
  ApprovalStatus,
  ApprovalResolution,
  ApprovalRequestRecord,
  ApprovalRequestCreateInput,
  AttachmentRecord,
  AttachmentCreateInput,
  AttachmentListOptions,
  AttachmentMaterializationPatch,
  AttachmentMaterializationState,
  AttachmentStorageProvider,
  ModelProviderRecord,
} from './types.js';

export { STANDALONE_AGENT_ID, standaloneScope, skillStorageId } from './types.js';

/**
 * Reserved session id for the per-agent owner inbox feed (read-only).
 * See `docs/inbox-design.md`.
 */
export const INBOX_SESSION_ID = 'inbox';

/**
 * Build a fresh inbox session entry for eager creation on agent register.
 */
export const buildInboxSessionEntry = (now: string): import('./types.js').PersistedSessionIndexEntry => ({
  sessionId: INBOX_SESSION_ID,
  source: { kind: 'inbox', interactive: false, platform: 'inbox' },
  status: 'idle',
  createdAt: now,
  lastActivityAt: now,
  messageCount: 0,
  completedTurnCount: 0,
  metadata: {},
  userIds: [],
});

export {
  DbInternalStateStore,
  DbSessionStore,
  DbMessageStore,
  DbMemoryProvider,
  DbInstructionStore,
  DbUserStore,
  DbAgentStore,
  DbAgentConfigStore,
  DbSkillStore,
  DbScheduleStore,
  DbMcpServerStore,
  FileSecretStore,
  DbSecretStore,
  DbAgentChannelStore,
  DbSandboxStore,
  DbPolicyStore,
  DbApprovalRequestStore,
  DbAttachmentStore,
  LocalAttachmentStorage,
  type LocalAttachmentStorageOptions,
  S3AttachmentStorage,
  type S3AttachmentStorageOptions,
  SupabaseAttachmentStorage,
  type SupabaseAttachmentStorageOptions,
  DbMetaStore,
  DbConsumedJtiStore,
  generateSecretsKey,
  runMigrations,
  DbGatewaySecretStore,
  DbModelProviderStore,
} from './impl/index.js';
