/**
 * Translation catalog. English is the source of truth — any new string
 * added to the UI MUST have an `en` entry. The `zh` entry is optional;
 * when missing, `t()` falls back to the English value so the UI never
 * shows a raw key.
 */

export type Locale = 'en' | 'zh';

export const LOCALES: { code: Locale; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '中文' },
];

export const DEFAULT_LOCALE: Locale = 'en';

export interface Messages {
  en: string;
  zh?: string;
}

export const messages = {
  // ── Common ────────────────────────────────────────────────────
  'common.loading': { en: 'Loading…', zh: '加载中…' },
  'common.cancel': { en: 'Cancel', zh: '取消' },
  'common.copy': { en: 'Copy', zh: '复制' },
  'common.unknown': { en: 'Unknown', zh: '未知' },
  'common.save': { en: 'Save', zh: '保存' },
  'common.saving': { en: 'Saving…', zh: '保存中…' },
  'common.delete': { en: 'Delete', zh: '删除' },
  'common.close': { en: 'Close', zh: '关闭' },
  'common.enable': { en: 'Enable', zh: '启用' },
  'common.disable': { en: 'Disable', zh: '停用' },
  'common.add': { en: 'Add', zh: '添加' },

  // ── Insecure context notice ───────────────────────────────────
  'insecure.title': { en: 'HTTPS required', zh: '需要 HTTPS' },
  'insecure.body1': {
    en: 'OpenHermit signs every request with a per-device ECDSA key generated by your browser. The key API (window.crypto.subtle) is only available over a secure context — that means HTTPS, http://localhost, or http://127.0.0.1.',
    zh: 'OpenHermit 使用浏览器为每台设备生成的 ECDSA 密钥对每个请求进行签名。该密钥 API（window.crypto.subtle）仅在安全上下文（HTTPS、http://localhost 或 http://127.0.0.1）中可用。',
  },
  'insecure.currentlyOn': { en: "You're currently on:", zh: '您当前的地址是：' },
  'insecure.howToFix': { en: 'To get a working URL:', zh: '获取可用地址的方式：' },
  'insecure.tailscale': {
    en: 'Use Tailscale Serve (tailscale serve --bg https://*) to front the web port with HTTPS over your tailnet.',
    zh: '使用 Tailscale Serve（tailscale serve --bg https://*）在 tailnet 上为 web 端口提供 HTTPS。',
  },
  'insecure.caddy': {
    en: "Put Caddy or nginx in front and let it auto-issue Let's Encrypt certs for your domain.",
    zh: '在前面部署 Caddy 或 nginx，让其为您的域名自动签发 Let\'s Encrypt 证书。',
  },
  'insecure.cloudflared': {
    en: 'Use a tunnel like cloudflared (cloudflared tunnel --url http://localhost:4310) — gives you HTTPS without opening ports.',
    zh: '使用 cloudflared 等隧道工具（cloudflared tunnel --url http://localhost:4310），无需开放端口即可获得 HTTPS。',
  },
  'insecure.localhost': {
    en: 'Or, if you only need local access, open http://127.0.0.1:4310 on the host machine itself.',
    zh: '若只需本机访问，可直接在宿主机打开 http://127.0.0.1:4310。',
  },

  // ── Setup screen ──────────────────────────────────────────────
  'setup.welcome': { en: 'Welcome', zh: '欢迎' },
  'setup.connectTitle': { en: 'Connect to Gateway', zh: '连接到 Gateway' },
  'setup.hintRestore': {
    en: 'Paste a device key you previously exported to restore access on this browser.',
    zh: '粘贴此前导出的设备密钥，可在当前浏览器恢复访问。',
  },
  'setup.hintNew': {
    en: 'A new device key has been generated for this browser. Tell us where the gateway is and what to call you.',
    zh: '已为当前浏览器生成新的设备密钥。请告诉我们 Gateway 地址和您的称呼。',
  },
  'setup.hintExisting': {
    en: 'Sign in to your gateway with this device key.',
    zh: '使用此设备密钥登录 Gateway。',
  },
  'setup.deviceKeyFingerprint': { en: 'Device Key Fingerprint', zh: '设备密钥指纹' },
  'setup.tabNew': { en: 'New device', zh: '新设备' },
  'setup.tabRestore': { en: 'Restore from key', zh: '从密钥恢复' },
  'setup.deviceKeyJsonLabel': { en: 'Device key (JSON)', zh: '设备密钥（JSON）' },
  'setup.deviceKeyJsonHelp': {
    en: 'Paste the full JSON you copied from Show access tokens → Device key on another browser. Display name will be restored from the file.',
    zh: '粘贴此前在其他浏览器从「显示访问令牌 → 设备密钥」复制的完整 JSON。显示名称会从该文件恢复。',
  },
  'setup.gatewayUrl': { en: 'Gateway URL', zh: 'Gateway 地址' },
  'setup.displayName': { en: 'Display Name', zh: '显示名称' },
  'setup.displayNamePlaceholder': { en: 'Your name', zh: '您的名字' },
  'setup.submitConnecting': { en: 'Connecting...', zh: '连接中…' },
  'setup.submitRestore': { en: 'Restore device', zh: '恢复设备' },
  'setup.submitNew': { en: 'Get started', zh: '开始使用' },
  'setup.submitContinue': { en: 'Continue', zh: '继续' },
  'setup.errInvalidKey': {
    en: "That doesn't look like a valid device key. Paste the full JSON you exported.",
    zh: '这看起来不是有效的设备密钥。请粘贴您导出的完整 JSON。',
  },
  'setup.errNameRequired': { en: 'Display name is required.', zh: '请输入显示名称。' },

  // ── Pick agent screen ─────────────────────────────────────────
  'pickAgent.title': { en: 'Pick an agent', zh: '选择 Agent' },
  'pickAgent.signedInAs': { en: 'Signed in as', zh: '当前登录：' },
  'pickAgent.gateway': { en: 'gateway:', zh: 'Gateway：' },
  'pickAgent.yourAgents': { en: 'Your agents', zh: '您的 Agent' },
  'pickAgent.empty': {
    en: 'No agent memberships yet — join one below.',
    zh: '尚未加入任何 Agent，您可以在下方加入一个。',
  },
  'pickAgent.disabledTitle': {
    en: 'This agent is disabled and cannot accept traffic.',
    zh: '该 Agent 已禁用，无法接收流量。',
  },
  'pickAgent.joinAnother': { en: '+ Join another agent', zh: '+ 加入其他 Agent' },
  'pickAgent.joinAnotherHeading': { en: 'Join another agent', zh: '加入其他 Agent' },
  'pickAgent.agentId': { en: 'Agent ID', zh: 'Agent ID' },
  'pickAgent.agentIdPlaceholder': { en: 'e.g. one', zh: '例如 one' },
  'pickAgent.inviteToken': { en: 'Agent invite token', zh: 'Agent 邀请令牌' },
  'pickAgent.inviteTokenPlaceholder': {
    en: 'Only if the agent is protected',
    zh: '仅当 Agent 受保护时才需要',
  },
  'pickAgent.inviteTokenHelp': {
    en: "Per-agent shared secret from the agent's owner (set with hermit agents create --access-token …). This is not your bearer token.",
    zh: '由 Agent 所有者提供的共享密钥（通过 hermit agents create --access-token … 设置）。这并不是您的 Bearer token。',
  },
  'pickAgent.joining': { en: 'Joining...', zh: '加入中…' },
  'pickAgent.join': { en: 'Join', zh: '加入' },
  'pickAgent.hideTokens': { en: 'Hide access tokens', zh: '隐藏访问令牌' },
  'pickAgent.showTokens': { en: 'Show access tokens', zh: '显示访问令牌' },
  'pickAgent.bearerTitle': { en: 'API bearer token (your JWT)', zh: 'API Bearer 令牌（您的 JWT）' },
  'pickAgent.bearerHelp': {
    en: "Short-lived (~24h). Use as Authorization: Bearer <token> for the CLI, curl, or any HTTP integration. Auto-refreshes from your device key when it expires. Don't paste this into the \"Agent invite token\" field when joining an agent — that field is a separate per-agent secret.",
    zh: '短期有效（约 24 小时）。在 CLI、curl 或任何 HTTP 集成中以 Authorization: Bearer <token> 使用。过期后会基于设备密钥自动刷新。请不要将其粘贴到「Agent 邀请令牌」字段——那是另一个独立的 Agent 共享密钥。',
  },
  'pickAgent.deviceKey': { en: 'Device key', zh: '设备密钥' },
  'pickAgent.hide': { en: 'Hide', zh: '隐藏' },
  'pickAgent.reveal': { en: 'Reveal', zh: '显示' },
  'pickAgent.fingerprintLabel': { en: 'Fingerprint:', zh: '指纹：' },
  'pickAgent.deviceKeyWarning': {
    en: '⚠ This is your private key. Anyone with it can sign in as you. Save it to a password manager to add another device — never paste it into chat or email.',
    zh: '⚠ 这是您的私钥。任何持有它的人都可以冒充您登录。请妥善保存在密码管理器中以便添加新设备——切勿粘贴到聊天或邮件中。',
  },
  'pickAgent.signOut': { en: 'Sign out', zh: '退出登录' },
  'pickAgent.copySuccess': { en: '{label} copied', zh: '{label} 已复制' },
  'pickAgent.copyFailed': {
    en: 'Copy failed — select and copy manually',
    zh: '复制失败，请手动选择并复制',
  },
  'pickAgent.bearerLabel': { en: 'Bearer token', zh: 'Bearer 令牌' },
  'pickAgent.deviceKeyLabel': { en: 'Device key', zh: '设备密钥' },

  // ── Connect screen ────────────────────────────────────────────
  'connect.title': { en: 'Connect to Agent', zh: '连接到 Agent' },
  'connect.at': { en: 'at', zh: '于' },
  'connect.gatewayPlaceholder': { en: 'http://localhost:4000', zh: 'http://localhost:4000' },
  'connect.agentIdPlaceholder': { en: 'one', zh: 'one' },
  'connect.accessToken': { en: 'Agent Access Token', zh: 'Agent 访问令牌' },
  'connect.accessTokenPlaceholder': {
    en: 'Only for protected agents',
    zh: '仅用于受保护的 Agent',
  },
  'connect.submit': { en: 'Connect', zh: '连接' },
  'connect.submitting': { en: 'Connecting...', zh: '连接中…' },

  // ── Chat shell ────────────────────────────────────────────────
  'chatShell.brandHome': { en: 'OpenHermit home', zh: 'OpenHermit 首页' },
  'chatShell.agentLabel': { en: 'Agent:', zh: 'Agent：' },
  'chatShell.inbox': { en: 'Inbox', zh: '收件箱' },
  'chatShell.unreadAria': { en: '{count} unread', zh: '{count} 条未读' },
  'chatShell.newSession': { en: 'New Session', zh: '新建会话' },
  'chatShell.manage': { en: 'Manage', zh: '管理' },
  'chatShell.observation': { en: 'Observation Mode', zh: '观察模式' },
  'chatShell.observationTitle': {
    en: "View other users' sessions on this agent",
    zh: '查看此 Agent 上其他用户的会话',
  },
  'chatShell.backToMy': { en: 'Back to my sessions', zh: '返回我的会话' },
  'chatShell.observeEmpty': {
    en: 'No other-user sessions on this agent yet.',
    zh: '当前 Agent 暂无其他用户的会话。',
  },
  'chatShell.footerAnonymous': { en: 'Anonymous', zh: '匿名' },
  'chatShell.footerAuth': { en: 'Auth: device key · WS', zh: '认证：设备密钥 · WebSocket' },
  'chatShell.disconnect': { en: 'Disconnect', zh: '断开连接' },
  'chatShell.backAria': { en: 'Back to sessions', zh: '返回会话列表' },
  'chatShell.eyebrowManage': { en: 'Agent Management', zh: 'Agent 管理' },
  'chatShell.eyebrowSession': { en: 'Current Session', zh: '当前会话' },
  'chatShell.noSession': { en: 'No session', zh: '未选择会话' },
  'chatShell.statusConnecting': { en: 'Connecting', zh: '连接中' },
  'chatShell.statusConnected': { en: 'Connected', zh: '已连接' },
  'chatShell.statusDisconnected': { en: 'Disconnected', zh: '已断开' },
  'chatShell.statusRunning': { en: 'Running', zh: '运行中' },
  'chatShell.readOnlyInbox': {
    en: 'Read-only — inbox is the owner notification feed',
    zh: '只读 — 收件箱是所有者的通知流',
  },
  'chatShell.readOnlyObserve': {
    en: 'Read-only — observing a session from {source}',
    zh: '只读 — 正在观察来自 {source} 的会话',
  },
  'chatShell.readOnlyExternal': {
    en: 'Read-only — this session was created via {source}',
    zh: '只读 — 该会话由 {source} 创建',
  },
  'chatShell.inboxEmpty': { en: 'No notifications yet.', zh: '暂无通知。' },
  'chatShell.sourceUnknown': { en: 'another channel', zh: '其他渠道' },
  'chatShell.deleteConfirm': {
    en: 'Delete this session? This cannot be undone.',
    zh: '确定要删除此会话吗？此操作不可撤销。',
  },

  // ── Session list ──────────────────────────────────────────────
  'sessionList.empty': {
    en: 'No sessions yet. Start one to begin chatting.',
    zh: '暂无会话。开始一个新会话即可对话。',
  },
  'sessionList.justNow': { en: 'just now', zh: '刚刚' },
  'sessionList.minutesAgo': { en: '{n}m ago', zh: '{n} 分钟前' },
  'sessionList.hoursAgo': { en: '{n}h ago', zh: '{n} 小时前' },
  'sessionList.daysAgo': { en: '{n}d ago', zh: '{n} 天前' },
  'sessionList.msgs': { en: '{n} msgs', zh: '{n} 条消息' },
  'sessionList.noPreview': { en: 'No preview yet', zh: '暂无预览' },
  'sessionList.deleteTitle': { en: 'Delete session', zh: '删除会话' },
  'sessionList.badgeApproval': { en: 'approval', zh: '待审批' },
  'sessionList.badgeRunning': { en: 'running', zh: '运行中' },

  // ── Composer ──────────────────────────────────────────────────
  'composer.placeholder': {
    en: 'Ask OpenHermit to inspect files, run code, search memory, or continue a previous thread...',
    zh: '请 OpenHermit 检查文件、运行代码、搜索记忆，或继续此前的对话…',
  },
  'composer.attachAvailable': { en: 'Attach files', zh: '附加文件' },
  'composer.attachUnavailable': { en: 'Attach files (unavailable)', zh: '附加文件（暂不可用）' },
  'composer.hintRunning': {
    en: 'Click Stop to interrupt the current turn.',
    zh: '点击「停止」以中断当前对话。',
  },
  'composer.hintUploading': { en: 'Uploading attachments…', zh: '正在上传附件…' },
  'composer.hintIdle': {
    en: 'Press Enter to send, Shift+Enter for newline.',
    zh: '按 Enter 发送，Shift+Enter 换行。',
  },
  'composer.stop': { en: 'Stop', zh: '停止' },
  'composer.send': { en: 'Send', zh: '发送' },
  'composer.removeAria': { en: 'Remove {name}', zh: '移除 {name}' },

  // ── Chat messages ─────────────────────────────────────────────
  'chatMessages.loadingHistory': { en: 'Loading session history', zh: '加载会话历史' },
  'chatMessages.empty': {
    en: 'Start a conversation or select a session from the sidebar.',
    zh: '开始对话，或在侧边栏中选择一个会话。',
  },
  'chatMessages.loadingAttachment': {
    en: 'Loading attachment {name}',
    zh: '加载附件 {name}',
  },
  'chatMessages.attachmentFailed': {
    en: '[attachment] failed to load {name}: {error}',
    zh: '[附件] 加载 {name} 失败：{error}',
  },
  'chatMessages.attachmentAlt': { en: 'attachment', zh: '附件' },
  'chatMessages.errorPrefix': { en: '[error] {text}', zh: '[错误] {text}' },
  'chatMessages.approvalRequired': {
    en: 'Approval required · {tool}',
    zh: '需要审批 · {tool}',
  },
  'chatMessages.noArguments': { en: 'No arguments', zh: '无参数' },
  'chatMessages.approve': { en: 'Approve', zh: '批准' },
  'chatMessages.deny': { en: 'Deny', zh: '拒绝' },
  'chatMessages.reject': { en: 'Reject', zh: '拒绝' },
  'chatMessages.approvedStatus': { en: '✅ Approved', zh: '✅ 已批准' },
  'chatMessages.rejectedStatus': { en: '✗ Rejected', zh: '✗ 已拒绝' },
  'chatMessages.approvedEvent': { en: '[approved] {tool}', zh: '[已批准] {tool}' },
  'chatMessages.deniedEvent': { en: '[denied] {tool}', zh: '[已拒绝] {tool}' },
  'chatMessages.you': { en: 'You', zh: '你' },
  'chatMessages.assistant': { en: 'Assistant', zh: '助手' },
  'chatMessages.thinking': { en: 'Thinking', zh: '思考中' },
  'chatMessages.introspection': { en: 'Introspection', zh: '内省' },
  'chatMessages.introspectionWithSummary': {
    en: 'Introspection — {summary}',
    zh: '内省 — {summary}',
  },
  'chatMessages.toolLabel': { en: 'Tool:', zh: '工具：' },
  'chatMessages.toolStatusDone': { en: 'done', zh: '完成' },
  'chatMessages.toolStatusError': { en: 'error', zh: '错误' },
  'chatMessages.toolStatusRunning': { en: 'running', zh: '运行中' },

  // ── Language switcher ─────────────────────────────────────────
  'lang.aria': { en: 'Switch language', zh: '切换语言' },

  // ── Manage panel tabs ─────────────────────────────────────────
  'manage.tab.basic': { en: 'Basic', zh: '基础' },
  'manage.tab.secrets': { en: 'Secrets', zh: '密钥' },
  'manage.tab.channels': { en: 'Channels', zh: '通道' },
  'manage.tab.voice': { en: 'Voice', zh: '语音' },
  'manage.tab.skills': { en: 'Skills', zh: '技能' },
  'manage.tab.mcp': { en: 'MCP Servers', zh: 'MCP 服务器' },
  'manage.tab.schedules': { en: 'Schedules', zh: '定时任务' },
  'manage.tab.policies': { en: 'Policies', zh: '策略' },
  'manage.tab.approvals': { en: 'Approvals', zh: '审批' },

  // ── Skills panel ──────────────────────────────────────────────
  'skills.empty': { en: 'No skills configured.', zh: '尚未配置技能。' },

  // ── MCP panel ─────────────────────────────────────────────────
  'mcp.empty': { en: 'No MCP servers enabled.', zh: '尚未启用 MCP 服务器。' },

  // ── Approvals panel ───────────────────────────────────────────
  'approvals.eyebrow': { en: 'Approval Requests', zh: '审批请求' },
  'approvals.hint': {
    en: 'When a tool has require_approval effect, users must request access. Approve or reject pending requests below.',
    zh: '当工具的效果为 require_approval 时，用户必须先申请访问。请在下方批准或拒绝待处理的请求。',
  },
  'approvals.filterAll': { en: 'All statuses', zh: '全部状态' },
  'approvals.statusPending': { en: 'Pending', zh: '待处理' },
  'approvals.statusApproved': { en: 'Approved', zh: '已批准' },
  'approvals.statusRejected': { en: 'Rejected', zh: '已拒绝' },
  'approvals.statusExpired': { en: 'Expired', zh: '已过期' },
  'approvals.emptyAll': { en: 'No approval requests.', zh: '暂无审批请求。' },
  'approvals.emptyFiltered': {
    en: 'No approval requests with status "{status}".',
    zh: '暂无状态为「{status}」的审批请求。',
  },
  'approvals.by': { en: 'by {requester}', zh: '请求者：{requester}' },
  'approvals.resolvedBy': { en: 'resolved by {resolver}', zh: '处理人：{resolver}' },
  'approvals.approveOnce': { en: 'Approve (once)', zh: '批准（仅本次）' },
  'approvals.approvePersistent': { en: 'Approve (persistent)', zh: '批准（永久）' },
  'approvals.approvePersistentTitle': {
    en: 'Approve and create a permanent allow policy',
    zh: '批准并创建永久允许的策略',
  },
  'approvals.reject': { en: 'Reject', zh: '拒绝' },

  // ── Schedules panel ───────────────────────────────────────────
  'schedules.empty': { en: 'No schedules.', zh: '暂无定时任务。' },
  'schedules.create': { en: 'Create Schedule', zh: '新建定时任务' },
  'schedules.runs': { en: 'Runs', zh: '运行记录' },
  'schedules.trigger': { en: 'Trigger', zh: '立即触发' },
  'schedules.pause': { en: 'Pause', zh: '暂停' },
  'schedules.resume': { en: 'Resume', zh: '恢复' },
  'schedules.deleteConfirm': { en: 'Delete schedule "{id}"?', zh: '删除定时任务「{id}」？' },
  'schedules.cron': { en: 'Cron: {expr}', zh: 'Cron：{expr}' },
  'schedules.runAt': { en: 'Run at: {time}', zh: '运行时间：{time}' },
  'schedules.next': { en: ' · Next: {time}', zh: ' · 下次：{time}' },
  'schedules.runCount': { en: ' · Runs: {n}', zh: ' · 已运行：{n} 次' },
  'schedules.errors': { en: ' · Errors: {n}', zh: ' · 错误：{n} 次' },
  'schedules.dialogTitle': { en: 'Create Schedule', zh: '新建定时任务' },
  'schedules.fieldIdOptional': { en: 'ID (optional)', zh: 'ID（可选）' },
  'schedules.idPlaceholder': { en: 'auto-generated if empty', zh: '留空自动生成' },
  'schedules.fieldType': { en: 'Type', zh: '类型' },
  'schedules.typeCron': { en: 'Cron', zh: '定时（Cron）' },
  'schedules.typeOnce': { en: 'Once', zh: '一次性' },
  'schedules.fieldPrompt': { en: 'Prompt', zh: '提示内容' },
  'schedules.fieldCron': { en: 'Cron Expression', zh: 'Cron 表达式' },
  'schedules.fieldRunAt': { en: 'Run At', zh: '运行时间' },
  'schedules.dialogCreate': { en: 'Create', zh: '创建' },
  'schedules.runsTitle': { en: 'Runs — {id}', zh: '运行记录 — {id}' },
  'schedules.runsEmpty': { en: 'No runs yet.', zh: '尚无运行记录。' },

  // ── Basic panel ───────────────────────────────────────────────
  'basic.eyebrow': { en: 'Model', zh: '模型' },
  'basic.hint': {
    en: 'Provider, model id, and thinking level. Other config (exec backend, memory, channels) remains unchanged.',
    zh: '配置 Provider、模型 ID 和思考级别。其他配置（执行后端、记忆、通道）保持不变。',
  },
  'basic.provider': { en: 'Provider', zh: 'Provider' },
  'basic.pickProvider': { en: '— pick a provider —', zh: '— 选择 Provider —' },
  'basic.providerOptionCounts': {
    en: '{flag} {provider} ({count})',
    zh: '{flag} {provider}（{count}）',
  },
  'basic.providerCustom': { en: 'Custom…', zh: '自定义…' },
  'basic.pickFromList': { en: 'Pick from list', zh: '从列表中选择' },
  'basic.providerCustomPlaceholder': {
    en: 'e.g. my-self-hosted-provider',
    zh: '例如：my-self-hosted-provider',
  },
  'basic.apiKeySet': { en: '✓ API key set: {name}', zh: '✓ 已设置 API Key：{name}' },
  'basic.apiKeyMissingPrefix': { en: '✗ No API key. Add ', zh: '✗ 未设置 API Key。请在 ' },
  'basic.apiKeyMissingSuffix': { en: ' in the Secrets tab.', zh: '「密钥」标签页中添加。' },
  'basic.baseUrl': { en: 'Base URL', zh: 'Base URL' },
  'basic.baseUrlHint': {
    en: 'Required for custom providers. The base URL of the API endpoint.',
    zh: '自定义 Provider 必填。API 端点的基础 URL。',
  },
  'basic.apiProtocol': { en: 'API protocol', zh: 'API 协议' },
  'basic.pickProtocol': { en: '— pick a protocol —', zh: '— 选择协议 —' },
  'basic.apiProtocolHint': {
    en: 'Required for custom providers not in the built-in registry.',
    zh: '内置注册表之外的自定义 Provider 必填。',
  },
  'basic.model': { en: 'Model', zh: '模型' },
  'basic.pickModel': { en: '— pick a model —', zh: '— 选择模型 —' },
  'basic.thinking': { en: 'Thinking', zh: '思考' },
  'basic.thinkingDefault': { en: '— default —', zh: '— 默认 —' },
  'basic.thinkingOffWarning': {
    en: '⚠️ {model} is a thinking model. Setting thinking to off on a thinking-only endpoint usually triggers 400 reasoning_content must be passed back once the session has any tool-call history. Pick a level (low / medium / high) instead, or leave as default — the server will apply medium automatically.',
    zh: '⚠️ {model} 是思考模型。在仅支持思考的端点上把 thinking 设为 off，会在会话出现任何工具调用历史后触发 400 reasoning_content must be passed back 错误。请选择 low / medium / high，或保留默认 — 服务器会自动应用 medium。',
  },
  'basic.thinkingDefaultNote': {
    en: '{model} is a thinking model — leaving the level at default will apply medium on the server.',
    zh: '{model} 是思考模型 — 级别保留默认时，服务器会应用 medium。',
  },
  'basic.savedAt': { en: 'Saved at {time}', zh: '已于 {time} 保存' },

  // ── Secrets panel ─────────────────────────────────────────────
  'secrets.eyebrow': { en: 'Secrets', zh: '密钥' },
  'secrets.hintPrefix': {
    en: 'Provider API keys, channel tokens, and other credentials. Existing values are never returned to the browser; the placeholder shows how the server has masked the current value. Each row saves independently — type a new value and click ',
    zh: 'Provider API Key、通道令牌等凭据。现有的值不会返回到浏览器；占位符显示的是服务器掩码后的当前值。每行独立保存 — 输入新值后点击该行上的「',
  },
  'secrets.hintMiddle1': { en: ' on that row, or ', zh: '」，或点击「' },
  'secrets.hintMiddle2': {
    en: ' to remove the secret. Toggle ',
    zh: '」删除该密钥。开启「',
  },
  'secrets.hintSuffix': {
    en: " to inject the secret as an environment variable into this agent's sandboxes at startup (takes effect on the next sandbox start).",
    zh: '」即可在该 agent 沙箱启动时将该密钥作为环境变量注入（下次沙箱启动后生效）。',
  },
  'secrets.add': { en: 'Add Secret', zh: '添加密钥' },
  'secrets.empty': { en: 'No secrets configured yet.', zh: '尚未配置密钥。' },
  'secrets.valueUnchanged': { en: 'unchanged', zh: '保持不变' },
  'secrets.passToSandbox': { en: 'Pass to sandbox', zh: '注入到沙箱' },
  'secrets.passToSandboxTitle': {
    en: 'Inject as env var into sandboxes',
    zh: '作为环境变量注入沙箱',
  },
  'secrets.passToSandboxAdd': {
    en: 'Pass to sandbox (inject as env var)',
    zh: '注入到沙箱（作为环境变量）',
  },
  'secrets.deleteConfirm': { en: 'Delete secret "{key}"?', zh: '删除密钥「{key}」？' },
  'secrets.dialogAddTitle': { en: 'Add Secret', zh: '添加密钥' },
  'secrets.fieldKey': { en: 'Key', zh: '名称' },
  'secrets.fieldValue': { en: 'Value', zh: '值' },
  'secrets.duplicateError': {
    en: 'Secret "{key}" already exists',
    zh: '密钥「{key}」已存在',
  },

  // ── Voice panel ───────────────────────────────────────────────
  'voice.eyebrow': { en: 'Voice', zh: '语音' },
  'voice.hint': {
    en: 'Speech-to-text (inbound voice messages) and text-to-speech (outbound replies). Each direction is independent — enable only what you need. Only ElevenLabs is supported in this build.',
    zh: '语音转文字（处理收到的语音消息）与文字转语音（合成回复）。两个方向相互独立，按需启用。当前版本仅支持 ElevenLabs。',
  },
  'voice.apiKeySet': { en: '✓ API key set: ', zh: '✓ 已设置 API Key：' },
  'voice.apiKeyMissingPrefix': { en: '✗ No API key. Add ', zh: '✗ 未设置 API Key。请在「密钥」标签页中添加 ' },
  'voice.apiKeyMissingSuffix': {
    en: ' in the Secrets tab before enabling voice.',
    zh: '，然后再启用语音。',
  },
  'voice.enableStt': { en: 'Enable speech-to-text (STT)', zh: '启用语音转文字（STT）' },
  'voice.sttHint': {
    en: 'Inbound voice messages from channels are transcribed before the agent sees them.',
    zh: '来自通道的语音消息会先被转写，再交给 agent 处理。',
  },
  'voice.sttModelLabel': { en: 'STT model id', zh: 'STT 模型 ID' },
  'voice.sttModelPlaceholder': { en: 'scribe_v1 (default)', zh: 'scribe_v1（默认）' },
  'voice.sttModelHintPrefix': {
    en: 'Optional. ElevenLabs Scribe model id. Leave blank for the default (',
    zh: '可选。ElevenLabs Scribe 模型 ID。留空使用默认值（',
  },
  'voice.sttModelHintSuffix': { en: ').', zh: '）。' },
  'voice.enableTts': { en: 'Enable text-to-speech (TTS)', zh: '启用文字转语音（TTS）' },
  'voice.ttsHint': {
    en: 'Final replies are synthesized and sent back as audio on channels that support voice.',
    zh: '最终回复会被合成为语音，发送到支持语音的通道。',
  },
  'voice.ttsVoiceLabel': { en: 'TTS voice id', zh: 'TTS 语音 ID' },
  'voice.ttsVoicePlaceholder': {
    en: '21m00Tcm4TlvDq8ikWAM (Rachel, default)',
    zh: '21m00Tcm4TlvDq8ikWAM（Rachel，默认）',
  },
  'voice.ttsVoiceHintPrefix': {
    en: 'Optional. The ElevenLabs voice id (from ',
    zh: '可选。ElevenLabs 的语音 ID（来源：',
  },
  'voice.ttsVoiceHintSuffix': {
    en: '). Leave blank to use the built-in default voice.',
    zh: '）。留空使用内置默认语音。',
  },
  'voice.ttsModelLabel': { en: 'TTS model id', zh: 'TTS 模型 ID' },
  'voice.ttsModelPlaceholder': {
    en: 'eleven_multilingual_v2 (default)',
    zh: 'eleven_multilingual_v2（默认）',
  },
  'voice.ttsModelHint': {
    en: 'Optional. ElevenLabs TTS model id. Leave blank for the default.',
    zh: '可选。ElevenLabs TTS 模型 ID。留空使用默认值。',
  },
  'voice.ttsSpeedLabel': { en: 'Speed', zh: '语速' },
  'voice.ttsSpeedPlaceholder': { en: '1.0 (default)', zh: '1.0（默认）' },
  'voice.ttsSpeedHint': {
    en: 'Optional playback rate multiplier; ~0.7–1.2 is typical. Leave blank for the provider default.',
    zh: '可选的播放速率倍数；常用范围 0.7–1.2。留空使用 Provider 默认。',
  },
  'voice.speedInvalid': {
    en: 'Speed must be a positive number.',
    zh: '语速必须是正数。',
  },

  // ── Policies panel ────────────────────────────────────────────
  'policies.eyebrow': { en: 'Access Policies', zh: '访问策略' },
  'policies.hint': {
    en: 'Control access to tools, MCP servers, and file paths. Each policy maps a resource to grants (who it applies to) and an effect (allow, deny, or require approval). Use * suffix for prefix matching.',
    zh: '控制对工具、MCP 服务器和文件路径的访问。每条策略将资源映射到授权（谁可使用）和效果（允许、拒绝或需审批）。前缀匹配请使用 * 后缀。',
  },
  'policies.add': { en: 'Add Policy', zh: '添加策略' },
  'policies.empty': {
    en: 'No custom policies. All tools use built-in defaults.',
    zh: '尚未配置自定义策略。所有工具使用内置默认值。',
  },
  'policies.deleteConfirm': {
    en: 'Delete policy for {type}/{key} [{effect}]?',
    zh: '删除策略 {type}/{key} [{effect}]？',
  },
  'policies.grantsNone': { en: 'None (blocked)', zh: '无（已阻止）' },
  'policies.grantsEveryone': { en: 'Everyone', zh: '所有人' },
  'policies.grantsUserPrefix': { en: 'user:', zh: '用户：' },
  'policies.resourceTool': { en: 'Tool', zh: '工具' },
  'policies.resourceMcp': { en: 'MCP Server', zh: 'MCP 服务器' },
  'policies.resourceFile': { en: 'File', zh: '文件' },
  'policies.dialogTitle': { en: 'Add Policy', zh: '添加策略' },
  'policies.fieldResourceType': { en: 'Resource type', zh: '资源类型' },
  'policies.fieldFilePath': { en: 'File path (prefix)', zh: '文件路径（前缀）' },
  'policies.filePathPlaceholder': {
    en: 'e.g. /root/notes.md, /home/user/',
    zh: '例如：/root/notes.md、/home/user/',
  },
  'policies.fieldMode': { en: 'Mode', zh: '模式' },
  'policies.modeAny': { en: 'Any (read + write)', zh: '任意（读 + 写）' },
  'policies.modeRead': { en: 'Read only', zh: '只读' },
  'policies.modeWrite': { en: 'Write only', zh: '只写' },
  'policies.fieldResourceKey': { en: 'Resource key', zh: '资源标识' },
  'policies.fieldEffect': { en: 'Effect', zh: '效果' },
  'policies.effectAllow': { en: 'Allow', zh: '允许' },
  'policies.effectDeny': { en: 'Deny', zh: '拒绝' },
  'policies.effectRequireApproval': { en: 'Require Approval', zh: '需要审批' },
  'policies.fieldGrants': { en: 'Grants (who this rule targets)', zh: '授权（规则适用对象）' },
  'policies.grantsEveryonePreset': { en: 'Everyone', zh: '所有人' },
  'policies.grantsOwnerOnly': { en: 'Owner only', zh: '仅 Owner' },
  'policies.grantsOwnerUser': { en: 'Owner + User', zh: 'Owner + User' },
  'policies.grantsCustomJson': { en: 'Custom JSON', zh: '自定义 JSON' },
  'policies.fieldCustomGrants': { en: 'Custom grants JSON', zh: '自定义授权 JSON' },
  'policies.grantsJsonError': {
    en: 'Grants must be a valid JSON array',
    zh: '授权必须是合法的 JSON 数组',
  },
  'policies.toolPlaceholder': {
    en: 'e.g. exec, file_write, memory_add',
    zh: '例如：exec、file_write、memory_add',
  },
  'policies.mcpPlaceholder': {
    en: 'e.g. weather, github, *',
    zh: '例如：weather、github、*',
  },
  'policies.filePlaceholder': {
    en: 'e.g. /etc/*, /home/user/.env',
    zh: '例如：/etc/*、/home/user/.env',
  },
} as const satisfies Record<string, Messages>;

export type MessageKey = keyof typeof messages;
