/**
 * Translation catalog. English is the source of truth — any new string
 * added to the UI MUST have an `en` entry. The `zh` entry is optional;
 * when missing, `t()` falls back to the English value so the UI never
 * shows a raw key.
 */

export type Locale = 'en' | 'zh';

export const LOCALES: { code: Locale; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '中文' },
];

export const DEFAULT_LOCALE: Locale = 'en';

export interface Messages {
  en: string;
  zh?: string;
}

export const messages = {
  // ── Common ────────────────────────────────────────────────────
  'common.loading': { en: 'Loading…', zh: '加载中…' },
  'common.cancel': { en: 'Cancel', zh: '取消' },
  'common.copy': { en: 'Copy', zh: '复制' },
  'common.unknown': { en: 'Unknown', zh: '未知' },

  // ── Insecure context notice ───────────────────────────────────
  'insecure.title': { en: 'HTTPS required', zh: '需要 HTTPS' },
  'insecure.body1': {
    en: 'OpenHermit signs every request with a per-device ECDSA key generated by your browser. The key API (window.crypto.subtle) is only available over a secure context — that means HTTPS, http://localhost, or http://127.0.0.1.',
    zh: 'OpenHermit 使用浏览器为每台设备生成的 ECDSA 密钥对每个请求进行签名。该密钥 API（window.crypto.subtle）仅在安全上下文（HTTPS、http://localhost 或 http://127.0.0.1）中可用。',
  },
  'insecure.currentlyOn': { en: "You're currently on:", zh: '您当前的地址是：' },
  'insecure.howToFix': { en: 'To get a working URL:', zh: '获取可用地址的方式：' },
  'insecure.tailscale': {
    en: 'Use Tailscale Serve (tailscale serve --bg https://*) to front the web port with HTTPS over your tailnet.',
    zh: '使用 Tailscale Serve（tailscale serve --bg https://*）在 tailnet 上为 web 端口提供 HTTPS。',
  },
  'insecure.caddy': {
    en: "Put Caddy or nginx in front and let it auto-issue Let's Encrypt certs for your domain.",
    zh: '在前面部署 Caddy 或 nginx，让其为您的域名自动签发 Let\'s Encrypt 证书。',
  },
  'insecure.cloudflared': {
    en: 'Use a tunnel like cloudflared (cloudflared tunnel --url http://localhost:4310) — gives you HTTPS without opening ports.',
    zh: '使用 cloudflared 等隧道工具（cloudflared tunnel --url http://localhost:4310），无需开放端口即可获得 HTTPS。',
  },
  'insecure.localhost': {
    en: 'Or, if you only need local access, open http://127.0.0.1:4310 on the host machine itself.',
    zh: '若只需本机访问，可直接在宿主机打开 http://127.0.0.1:4310。',
  },

  // ── Setup screen ──────────────────────────────────────────────
  'setup.welcome': { en: 'Welcome', zh: '欢迎' },
  'setup.connectTitle': { en: 'Connect to Gateway', zh: '连接到 Gateway' },
  'setup.hintRestore': {
    en: 'Paste a device key you previously exported to restore access on this browser.',
    zh: '粘贴此前导出的设备密钥，可在当前浏览器恢复访问。',
  },
  'setup.hintNew': {
    en: 'A new device key has been generated for this browser. Tell us where the gateway is and what to call you.',
    zh: '已为当前浏览器生成新的设备密钥。请告诉我们 Gateway 地址和您的称呼。',
  },
  'setup.hintExisting': {
    en: 'Sign in to your gateway with this device key.',
    zh: '使用此设备密钥登录 Gateway。',
  },
  'setup.deviceKeyFingerprint': { en: 'Device Key Fingerprint', zh: '设备密钥指纹' },
  'setup.tabNew': { en: 'New device', zh: '新设备' },
  'setup.tabRestore': { en: 'Restore from key', zh: '从密钥恢复' },
  'setup.deviceKeyJsonLabel': { en: 'Device key (JSON)', zh: '设备密钥（JSON）' },
  'setup.deviceKeyJsonHelp': {
    en: 'Paste the full JSON you copied from Show access tokens → Device key on another browser. Display name will be restored from the file.',
    zh: '粘贴此前在其他浏览器从「显示访问令牌 → 设备密钥」复制的完整 JSON。显示名称会从该文件恢复。',
  },
  'setup.gatewayUrl': { en: 'Gateway URL', zh: 'Gateway 地址' },
  'setup.displayName': { en: 'Display Name', zh: '显示名称' },
  'setup.displayNamePlaceholder': { en: 'Your name', zh: '您的名字' },
  'setup.submitConnecting': { en: 'Connecting...', zh: '连接中…' },
  'setup.submitRestore': { en: 'Restore device', zh: '恢复设备' },
  'setup.submitNew': { en: 'Get started', zh: '开始使用' },
  'setup.submitContinue': { en: 'Continue', zh: '继续' },
  'setup.errInvalidKey': {
    en: "That doesn't look like a valid device key. Paste the full JSON you exported.",
    zh: '这看起来不是有效的设备密钥。请粘贴您导出的完整 JSON。',
  },
  'setup.errNameRequired': { en: 'Display name is required.', zh: '请输入显示名称。' },

  // ── Pick agent screen ─────────────────────────────────────────
  'pickAgent.title': { en: 'Pick an agent', zh: '选择 Agent' },
  'pickAgent.signedInAs': { en: 'Signed in as', zh: '当前登录：' },
  'pickAgent.gateway': { en: 'gateway:', zh: 'Gateway：' },
  'pickAgent.yourAgents': { en: 'Your agents', zh: '您的 Agent' },
  'pickAgent.empty': {
    en: 'No agent memberships yet — join one below.',
    zh: '尚未加入任何 Agent，您可以在下方加入一个。',
  },
  'pickAgent.disabledTitle': {
    en: 'This agent is disabled and cannot accept traffic.',
    zh: '该 Agent 已禁用，无法接收流量。',
  },
  'pickAgent.joinAnother': { en: '+ Join another agent', zh: '+ 加入其他 Agent' },
  'pickAgent.joinAnotherHeading': { en: 'Join another agent', zh: '加入其他 Agent' },
  'pickAgent.agentId': { en: 'Agent ID', zh: 'Agent ID' },
  'pickAgent.agentIdPlaceholder': { en: 'e.g. one', zh: '例如 one' },
  'pickAgent.inviteToken': { en: 'Agent invite token', zh: 'Agent 邀请令牌' },
  'pickAgent.inviteTokenPlaceholder': {
    en: 'Only if the agent is protected',
    zh: '仅当 Agent 受保护时才需要',
  },
  'pickAgent.inviteTokenHelp': {
    en: "Per-agent shared secret from the agent's owner (set with hermit agents create --access-token …). This is not your bearer token.",
    zh: '由 Agent 所有者提供的共享密钥（通过 hermit agents create --access-token … 设置）。这并不是您的 Bearer token。',
  },
  'pickAgent.joining': { en: 'Joining...', zh: '加入中…' },
  'pickAgent.join': { en: 'Join', zh: '加入' },
  'pickAgent.hideTokens': { en: 'Hide access tokens', zh: '隐藏访问令牌' },
  'pickAgent.showTokens': { en: 'Show access tokens', zh: '显示访问令牌' },
  'pickAgent.bearerTitle': { en: 'API bearer token (your JWT)', zh: 'API Bearer 令牌（您的 JWT）' },
  'pickAgent.bearerHelp': {
    en: "Short-lived (~24h). Use as Authorization: Bearer <token> for the CLI, curl, or any HTTP integration. Auto-refreshes from your device key when it expires. Don't paste this into the \"Agent invite token\" field when joining an agent — that field is a separate per-agent secret.",
    zh: '短期有效（约 24 小时）。在 CLI、curl 或任何 HTTP 集成中以 Authorization: Bearer <token> 使用。过期后会基于设备密钥自动刷新。请不要将其粘贴到「Agent 邀请令牌」字段——那是另一个独立的 Agent 共享密钥。',
  },
  'pickAgent.deviceKey': { en: 'Device key', zh: '设备密钥' },
  'pickAgent.hide': { en: 'Hide', zh: '隐藏' },
  'pickAgent.reveal': { en: 'Reveal', zh: '显示' },
  'pickAgent.fingerprintLabel': { en: 'Fingerprint:', zh: '指纹：' },
  'pickAgent.deviceKeyWarning': {
    en: '⚠ This is your private key. Anyone with it can sign in as you. Save it to a password manager to add another device — never paste it into chat or email.',
    zh: '⚠ 这是您的私钥。任何持有它的人都可以冒充您登录。请妥善保存在密码管理器中以便添加新设备——切勿粘贴到聊天或邮件中。',
  },
  'pickAgent.signOut': { en: 'Sign out', zh: '退出登录' },
  'pickAgent.copySuccess': { en: '{label} copied', zh: '{label} 已复制' },
  'pickAgent.copyFailed': {
    en: 'Copy failed — select and copy manually',
    zh: '复制失败，请手动选择并复制',
  },
  'pickAgent.bearerLabel': { en: 'Bearer token', zh: 'Bearer 令牌' },
  'pickAgent.deviceKeyLabel': { en: 'Device key', zh: '设备密钥' },

  // ── Connect screen ────────────────────────────────────────────
  'connect.title': { en: 'Connect to Agent', zh: '连接到 Agent' },
  'connect.at': { en: 'at', zh: '于' },
  'connect.gatewayPlaceholder': { en: 'http://localhost:4000', zh: 'http://localhost:4000' },
  'connect.agentIdPlaceholder': { en: 'one', zh: 'one' },
  'connect.accessToken': { en: 'Agent Access Token', zh: 'Agent 访问令牌' },
  'connect.accessTokenPlaceholder': {
    en: 'Only for protected agents',
    zh: '仅用于受保护的 Agent',
  },
  'connect.submit': { en: 'Connect', zh: '连接' },
  'connect.submitting': { en: 'Connecting...', zh: '连接中…' },

  // ── Chat shell ────────────────────────────────────────────────
  'chatShell.brandHome': { en: 'OpenHermit home', zh: 'OpenHermit 首页' },
  'chatShell.agentLabel': { en: 'Agent:', zh: 'Agent：' },
  'chatShell.inbox': { en: 'Inbox', zh: '收件箱' },
  'chatShell.unreadAria': { en: '{count} unread', zh: '{count} 条未读' },
  'chatShell.newSession': { en: 'New Session', zh: '新建会话' },
  'chatShell.manage': { en: 'Manage', zh: '管理' },
  'chatShell.observation': { en: 'Observation Mode', zh: '观察模式' },
  'chatShell.observationTitle': {
    en: "View other users' sessions on this agent",
    zh: '查看此 Agent 上其他用户的会话',
  },
  'chatShell.backToMy': { en: 'Back to my sessions', zh: '返回我的会话' },
  'chatShell.observeEmpty': {
    en: 'No other-user sessions on this agent yet.',
    zh: '当前 Agent 暂无其他用户的会话。',
  },
  'chatShell.footerAnonymous': { en: 'Anonymous', zh: '匿名' },
  'chatShell.footerAuth': { en: 'Auth: device key · WS', zh: '认证：设备密钥 · WebSocket' },
  'chatShell.disconnect': { en: 'Disconnect', zh: '断开连接' },
  'chatShell.backAria': { en: 'Back to sessions', zh: '返回会话列表' },
  'chatShell.eyebrowManage': { en: 'Agent Management', zh: 'Agent 管理' },
  'chatShell.eyebrowSession': { en: 'Current Session', zh: '当前会话' },
  'chatShell.noSession': { en: 'No session', zh: '未选择会话' },
  'chatShell.statusConnecting': { en: 'Connecting', zh: '连接中' },
  'chatShell.statusConnected': { en: 'Connected', zh: '已连接' },
  'chatShell.statusDisconnected': { en: 'Disconnected', zh: '已断开' },
  'chatShell.statusRunning': { en: 'Running', zh: '运行中' },
  'chatShell.readOnlyInbox': {
    en: 'Read-only — inbox is the owner notification feed',
    zh: '只读 — 收件箱是所有者的通知流',
  },
  'chatShell.readOnlyObserve': {
    en: 'Read-only — observing a session from {source}',
    zh: '只读 — 正在观察来自 {source} 的会话',
  },
  'chatShell.readOnlyExternal': {
    en: 'Read-only — this session was created via {source}',
    zh: '只读 — 该会话由 {source} 创建',
  },
  'chatShell.inboxEmpty': { en: 'No notifications yet.', zh: '暂无通知。' },
  'chatShell.sourceUnknown': { en: 'another channel', zh: '其他渠道' },
  'chatShell.deleteConfirm': {
    en: 'Delete this session? This cannot be undone.',
    zh: '确定要删除此会话吗？此操作不可撤销。',
  },

  // ── Session list ──────────────────────────────────────────────
  'sessionList.empty': {
    en: 'No sessions yet. Start one to begin chatting.',
    zh: '暂无会话。开始一个新会话即可对话。',
  },
  'sessionList.justNow': { en: 'just now', zh: '刚刚' },
  'sessionList.minutesAgo': { en: '{n}m ago', zh: '{n} 分钟前' },
  'sessionList.hoursAgo': { en: '{n}h ago', zh: '{n} 小时前' },
  'sessionList.daysAgo': { en: '{n}d ago', zh: '{n} 天前' },
  'sessionList.msgs': { en: '{n} msgs', zh: '{n} 条消息' },
  'sessionList.noPreview': { en: 'No preview yet', zh: '暂无预览' },
  'sessionList.deleteTitle': { en: 'Delete session', zh: '删除会话' },
  'sessionList.badgeApproval': { en: 'approval', zh: '待审批' },
  'sessionList.badgeRunning': { en: 'running', zh: '运行中' },

  // ── Composer ──────────────────────────────────────────────────
  'composer.placeholder': {
    en: 'Ask OpenHermit to inspect files, run code, search memory, or continue a previous thread...',
    zh: '请 OpenHermit 检查文件、运行代码、搜索记忆，或继续此前的对话…',
  },
  'composer.attachAvailable': { en: 'Attach files', zh: '附加文件' },
  'composer.attachUnavailable': { en: 'Attach files (unavailable)', zh: '附加文件（暂不可用）' },
  'composer.hintRunning': {
    en: 'Click Stop to interrupt the current turn.',
    zh: '点击「停止」以中断当前对话。',
  },
  'composer.hintUploading': { en: 'Uploading attachments…', zh: '正在上传附件…' },
  'composer.hintIdle': {
    en: 'Press Enter to send, Shift+Enter for newline.',
    zh: '按 Enter 发送，Shift+Enter 换行。',
  },
  'composer.stop': { en: 'Stop', zh: '停止' },
  'composer.send': { en: 'Send', zh: '发送' },
  'composer.removeAria': { en: 'Remove {name}', zh: '移除 {name}' },

  // ── Chat messages ─────────────────────────────────────────────
  'chatMessages.loadingHistory': { en: 'Loading session history', zh: '加载会话历史' },
  'chatMessages.empty': {
    en: 'Start a conversation or select a session from the sidebar.',
    zh: '开始对话，或在侧边栏中选择一个会话。',
  },
  'chatMessages.loadingAttachment': {
    en: 'Loading attachment {name}',
    zh: '加载附件 {name}',
  },
  'chatMessages.attachmentFailed': {
    en: '[attachment] failed to load {name}: {error}',
    zh: '[附件] 加载 {name} 失败：{error}',
  },
  'chatMessages.attachmentAlt': { en: 'attachment', zh: '附件' },
  'chatMessages.errorPrefix': { en: '[error] {text}', zh: '[错误] {text}' },
  'chatMessages.approvalRequired': {
    en: 'Approval required · {tool}',
    zh: '需要审批 · {tool}',
  },
  'chatMessages.noArguments': { en: 'No arguments', zh: '无参数' },
  'chatMessages.approve': { en: 'Approve', zh: '批准' },
  'chatMessages.deny': { en: 'Deny', zh: '拒绝' },
  'chatMessages.reject': { en: 'Reject', zh: '拒绝' },
  'chatMessages.approvedStatus': { en: '✅ Approved', zh: '✅ 已批准' },
  'chatMessages.rejectedStatus': { en: '✗ Rejected', zh: '✗ 已拒绝' },
  'chatMessages.approvedEvent': { en: '[approved] {tool}', zh: '[已批准] {tool}' },
  'chatMessages.deniedEvent': { en: '[denied] {tool}', zh: '[已拒绝] {tool}' },
  'chatMessages.you': { en: 'You', zh: '你' },
  'chatMessages.assistant': { en: 'Assistant', zh: '助手' },
  'chatMessages.thinking': { en: 'Thinking', zh: '思考中' },
  'chatMessages.introspection': { en: 'Introspection', zh: '内省' },
  'chatMessages.introspectionWithSummary': {
    en: 'Introspection — {summary}',
    zh: '内省 — {summary}',
  },
  'chatMessages.toolLabel': { en: 'Tool:', zh: '工具：' },
  'chatMessages.toolStatusDone': { en: 'done', zh: '完成' },
  'chatMessages.toolStatusError': { en: 'error', zh: '错误' },
  'chatMessages.toolStatusRunning': { en: 'running', zh: '运行中' },

  // ── Language switcher ─────────────────────────────────────────
  'lang.aria': { en: 'Switch language', zh: '切换语言' },
} as const satisfies Record<string, Messages>;

export type MessageKey = keyof typeof messages;
